/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationResultDto } from './models/authentication-result-dto';
export type { BookingCreateByReceptionDto } from './models/booking-create-by-reception-dto';
export type { BookingCreateDto } from './models/booking-create-dto';
export type { BookingDto } from './models/booking-dto';
export type { BookingDtoPagedResult } from './models/booking-dto-paged-result';
export { BookingStatus } from './models/booking-status';
export type { BookingUpdateDto } from './models/booking-update-dto';
export type { InvoiceDto } from './models/invoice-dto';
export type { InvoiceItemCreateDto } from './models/invoice-item-create-dto';
export type { InvoiceItemDto } from './models/invoice-item-dto';
export { InvoiceItemType } from './models/invoice-item-type';
export { InvoiceStatus } from './models/invoice-status';
export type { LoginRequestDto } from './models/login-request-dto';
export type { PaymentDto } from './models/payment-dto';
export { PaymentMethod } from './models/payment-method';
export type { ProblemDetails } from './models/problem-details';
export type { RegisterRequestDto } from './models/register-request-dto';
export type { RoomDto } from './models/room-dto';
export { RoomStatus } from './models/room-status';
export type { RoomTypeDto } from './models/room-type-dto';
export type { RoomTypeUpsertDto } from './models/room-type-upsert-dto';
export type { RoomUpsertDto } from './models/room-upsert-dto';
export type { ServiceDto } from './models/service-dto';
export type { ServiceUpsertDto } from './models/service-upsert-dto';
export type { UserBookingsDto } from './models/user-bookings-dto';
export type { UserBookingsDtoPagedResult } from './models/user-bookings-dto-paged-result';
export type { UserDto } from './models/user-dto';
export { UserRole } from './models/user-role';
export type { UserUpdateDto } from './models/user-update-dto';
