/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomTypeDto } from '../../models/room-type-dto';
import { RoomTypeUpsertDto } from '../../models/room-type-upsert-dto';

export interface CreateRoomType$Plain$Params {
  
    /**
     * The room type creation data transfer object.
     */
    body?: RoomTypeUpsertDto
}

export function createRoomType$Plain(http: HttpClient, rootUrl: string, params?: CreateRoomType$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomTypeDto>> {
  const rb = new RequestBuilder(rootUrl, createRoomType$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoomTypeDto>;
    })
  );
}

createRoomType$Plain.PATH = '/api/RoomTypes';
