/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PayOnline$Plain$Params {

/**
 * The unique identifier of the invoice to be paid.
 */
  invoiceId: number;
}

export function payOnline$Plain(http: HttpClient, rootUrl: string, params: PayOnline$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, payOnline$Plain.PATH, 'post');
  if (params) {
    rb.path('invoiceId', params.invoiceId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

payOnline$Plain.PATH = '/api/Payments/{invoiceId}/online';
