/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceDto } from '../../models/invoice-dto';

export interface PaymentsRefund$Params {

/**
 * The unique identifier of the invoice for which a refund is requested.
 */
  invoiceId: number;
}

export function paymentsRefund(http: HttpClient, rootUrl: string, params: PaymentsRefund$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceDto>> {
  const rb = new RequestBuilder(rootUrl, paymentsRefund.PATH, 'post');
  if (params) {
    rb.path('invoiceId', params.invoiceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceDto>;
    })
  );
}

paymentsRefund.PATH = '/api/Payments/{invoiceId}/refund';
