/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingDto } from '../../models/booking-dto';

export interface BookingsCancelBooking$Plain$Params {

/**
 * The unique identifier of the booking to cancel.
 */
  id: number;
}

export function bookingsCancelBooking$Plain(http: HttpClient, rootUrl: string, params: BookingsCancelBooking$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingDto>> {
  const rb = new RequestBuilder(rootUrl, bookingsCancelBooking$Plain.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingDto>;
    })
  );
}

bookingsCancelBooking$Plain.PATH = '/api/Bookings/{id}/cancel';
