/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingDto } from '../../models/booking-dto';

export interface BookingsGetBookings$Params {
}

export function bookingsGetBookings(http: HttpClient, rootUrl: string, params?: BookingsGetBookings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingDto>>> {
  const rb = new RequestBuilder(rootUrl, bookingsGetBookings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookingDto>>;
    })
  );
}

bookingsGetBookings.PATH = '/api/Bookings';
