/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingDto } from '../../models/booking-dto';

export interface BookingsGetBookingById$Params {

/**
 * The unique identifier of the booking.
 */
  id: number;
}

export function bookingsGetBookingById(http: HttpClient, rootUrl: string, params: BookingsGetBookingById$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingDto>> {
  const rb = new RequestBuilder(rootUrl, bookingsGetBookingById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingDto>;
    })
  );
}

bookingsGetBookingById.PATH = '/api/Bookings/{id}';
