/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingCreateDto } from '../../models/booking-create-dto';
import { BookingDto } from '../../models/booking-dto';

export interface CreateBooking$Params {
  
    /**
     * The booking creation data transfer object.
     */
    body?: BookingCreateDto
}

export function createBooking(http: HttpClient, rootUrl: string, params?: CreateBooking$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingDto>> {
  const rb = new RequestBuilder(rootUrl, createBooking.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingDto>;
    })
  );
}

createBooking.PATH = '/api/Bookings';
