/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserBookingsDto } from '../../models/user-bookings-dto';

export interface GetUserBookings$Plain$Params {
}

export function getUserBookings$Plain(http: HttpClient, rootUrl: string, params?: GetUserBookings$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserBookingsDto>>> {
  const rb = new RequestBuilder(rootUrl, getUserBookings$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserBookingsDto>>;
    })
  );
}

getUserBookings$Plain.PATH = '/api/Bookings/user';
