/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserBookingsDtoPagedResult } from '../../models/user-bookings-dto-paged-result';

export interface GetUserBookings$Plain$Params {

/**
 * The number of the page to retrieve (default is 1).
 */
  pageNumber?: number;

/**
 * The number of bookings to include per page (default is 10).
 */
  pageSize?: number;
}

export function getUserBookings$Plain(http: HttpClient, rootUrl: string, params?: GetUserBookings$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserBookingsDtoPagedResult>> {
  const rb = new RequestBuilder(rootUrl, getUserBookings$Plain.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserBookingsDtoPagedResult>;
    })
  );
}

getUserBookings$Plain.PATH = '/api/Bookings/user';
