/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingStatus } from '../models/booking-status';
import { DateOnly } from '../models/date-only';
export interface BookingDto {
  bookingId?: number;
  bookingStatus?: BookingStatus;
  endDate?: DateOnly;
  roomNumber?: string | null;
  startDate?: DateOnly;
  userId?: string | null;
}
