/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingStatus } from '../models/booking-status';
import { PaymentMethod } from '../models/payment-method';
export interface BookingDto {
  bookingId?: number;
  bookingStatus?: BookingStatus;
  endDate?: string;
  fullName?: string | null;
  invoiceId?: number;
  paymentMethod?: PaymentMethod;
  phoneNumber?: string | null;
  roomCategory?: string | null;
  roomNumber?: string | null;
  startDate?: string;
}
