/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum InvoiceStatus {
  Paid = 'Paid',
  Pending = 'Pending',
  PartiallyPaid = 'PartiallyPaid',
  Cancelled = 'Cancelled',
  Refunded = 'Refunded',
  Undefined = 'Undefined'
}
