/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceItemType } from '../models/invoice-item-type';
export interface InvoiceItemDto {
  createdAt?: string;
  description?: string | null;
  invoiceItemId?: number;
  invoiceItemType?: InvoiceItemType;
  isLocked?: boolean;
  lineTotal?: number;
  quantity?: number;
  serviceName?: string | null;
  unitPrice?: number;
}
