/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum InvoiceItemType {
  RoomBooking = 'RoomBooking',
  AdditionalService = 'AdditionalService'
}
