/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceItemDto } from '../models/invoice-item-dto';
import { InvoiceStatus } from '../models/invoice-status';
export interface InvoiceDto {
  bookingId?: number;
  createdAt?: string;
  invoiceId?: number;
  invoiceItems?: Array<InvoiceItemDto> | null;
  status?: InvoiceStatus;
  totalAmount?: number;
}
