/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceItemDto {
  description?: string | null;
  invoiceItemId?: number;
  lineTotal?: number;
  quantity?: number;
  serviceName?: string | null;
  unitPrice?: number;
}
