/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum InvoiceStatus {
  Paid = 'Paid',
  Pending = 'Pending',
  Cancelled = 'Cancelled',
  Refunded = 'Refunded',
  Undefiend = 'Undefiend'
}
