/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceItemCreateDto {
  description?: string | null;
  quantity?: number;
  serviceName: string;
}
