/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMethod } from '../models/payment-method';
export interface PaymentDto {
  amount?: number;
  externalId?: string | null;
  invoiceId?: number;
  method?: PaymentMethod;
  paidAt?: string;
  paymentId?: number;
}
