/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomCategory } from '../models/room-category';
export interface RoomTypeDto {
  category?: RoomCategory;
  description?: string | null;
  pricePerNight?: number;
  roomTypeId?: number;
}
