/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomTypeUpsertDto {
  description: string;
  imageUrl?: string | null;
  pricePerNight?: number;
  roomCategory: string;
}
