/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum RoomCategory {
  Single = 'Single',
  Double = 'Double',
  Family = 'Family',
  Suite = 'Suite'
}
