/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomCategory } from '../models/room-category';
import { RoomStatus } from '../models/room-status';
export interface RoomDto {
  description?: string | null;
  imageUrl?: string | null;
  pricePerDay?: number;
  roomId?: number;
  roomNumber?: string | null;
  roomStatus?: RoomStatus;
  roomType?: RoomCategory;
}
