/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomTypeDto {
  description?: string | null;
  pricePerNight?: number;
  roomCategory?: string | null;
  roomTypeId?: number;
}
