/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomCategory } from '../models/room-category';
import { RoomStatus } from '../models/room-status';
export interface RoomUpsertDto {
  roomNumber: string;
  roomStatus: RoomStatus;
  roomType: RoomCategory;
}
