/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomStatus } from '../models/room-status';
export interface RoomDto {
  pricePerDay?: number;
  roomCategory?: string | null;
  roomId?: number;
  roomNumber?: string | null;
  roomStatus?: RoomStatus;
  roomTypeId?: number;
}
