/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomStatus } from '../models/room-status';
export interface RoomUpsertDto {
  roomNumber: string;
  roomStatus: RoomStatus;
  roomTypeId: number;
}
