/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceUpsertDto {
  description?: string | null;
  isAvailable: boolean;
  name: string;
  price?: number;
}
