/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceDto {
  description?: string | null;
  isAvailable?: boolean;
  name?: string | null;
  price?: number;
  serviceId?: number;
}
