/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingStatus } from '../models/booking-status';
import { RoomCategory } from '../models/room-category';
export interface UserBookingsDto {
  amount?: number;
  bookingId?: number;
  bookingStatus?: BookingStatus;
  endDate?: string;
  roomCategory?: RoomCategory;
  roomNumber?: string | null;
  startDate?: string;
}
