/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthenticationResultDto } from '../models/authentication-result-dto';
import { login } from '../fn/auth/login';
import { Login$Params } from '../fn/auth/login';
import { login$Plain } from '../fn/auth/login-plain';
import { Login$Plain$Params } from '../fn/auth/login-plain';
import { register } from '../fn/auth/register';
import { Register$Params } from '../fn/auth/register';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/api/Auth/register';

  /**
   * Registers a new user based on provided registration details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  register$Response(params?: Register$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return register(this.http, this.rootUrl, params, context);
  }

  /**
   * Registers a new user based on provided registration details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  register(params?: Register$Params, context?: HttpContext): Observable<void> {
    return this.register$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/Auth/login';

  /**
   * Authenticates an existing user using email and password.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  login$Plain$Response(params?: Login$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResultDto>> {
    return login$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Authenticates an existing user using email and password.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  login$Plain(params?: Login$Plain$Params, context?: HttpContext): Observable<AuthenticationResultDto> {
    return this.login$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResultDto>): AuthenticationResultDto => r.body)
    );
  }

  /**
   * Authenticates an existing user using email and password.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  login$Response(params?: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResultDto>> {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * Authenticates an existing user using email and password.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  login(params?: Login$Params, context?: HttpContext): Observable<AuthenticationResultDto> {
    return this.login$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResultDto>): AuthenticationResultDto => r.body)
    );
  }

}
