/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomDto } from '../../models/room-dto';
import { RoomStatus } from '../../models/room-status';

export interface UpdateStatus_1$Params {

/**
 * The unique identifier of the room.
 */
  id: number;

/**
 * The new status for the room.
 */
  newStatus?: RoomStatus;
}

export function updateStatus_1(http: HttpClient, rootUrl: string, params: UpdateStatus_1$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomDto>> {
  const rb = new RequestBuilder(rootUrl, updateStatus_1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('newStatus', params.newStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoomDto>;
    })
  );
}

updateStatus_1.PATH = '/api/Rooms/{id}/status';
