/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthenticationResultDto } from '../../models/authentication-result-dto';
import { RegisterRequestDto } from '../../models/register-request-dto';

export interface AuthRegister$Params {
  
    /**
     * The registration request data containing user information.
     */
    body?: RegisterRequestDto
}

export function authRegister(http: HttpClient, rootUrl: string, params?: AuthRegister$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResultDto>> {
  const rb = new RequestBuilder(rootUrl, authRegister.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthenticationResultDto>;
    })
  );
}

authRegister.PATH = '/api/Auth/register';
