/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceDto } from '../../models/invoice-dto';
import { InvoiceItemCreateDto } from '../../models/invoice-item-create-dto';

export interface AddInvoiceItem$Plain$Params {

/**
 * The unique identifier of the invoice.
 */
  invoiceId: number;
  
    /**
     * The data needed to create the invoice item.
     */
    body?: InvoiceItemCreateDto
}

export function addInvoiceItem$Plain(http: HttpClient, rootUrl: string, params: AddInvoiceItem$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceDto>> {
  const rb = new RequestBuilder(rootUrl, addInvoiceItem$Plain.PATH, 'post');
  if (params) {
    rb.path('invoiceId', params.invoiceId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceDto>;
    })
  );
}

addInvoiceItem$Plain.PATH = '/api/Invoices/{invoiceId}/items';
