/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceDto } from '../../models/invoice-dto';

export interface CreateInvoice$Plain$Params {

/**
 * The unique identifier of the booking.
 */
  bookingId: number;
}

export function createInvoice$Plain(http: HttpClient, rootUrl: string, params: CreateInvoice$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceDto>> {
  const rb = new RequestBuilder(rootUrl, createInvoice$Plain.PATH, 'post');
  if (params) {
    rb.path('bookingId', params.bookingId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceDto>;
    })
  );
}

createInvoice$Plain.PATH = '/api/Invoices/{bookingId}';
