/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceDto } from '../../models/invoice-dto';
import { InvoiceStatus } from '../../models/invoice-status';

export interface UpdateInvoiceStatus$Params {

/**
 * The unique identifier of the invoice.
 */
  id: number;

/**
 * The new status to be applied.
 */
  status?: InvoiceStatus;
}

export function updateInvoiceStatus(http: HttpClient, rootUrl: string, params: UpdateInvoiceStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceDto>> {
  const rb = new RequestBuilder(rootUrl, updateInvoiceStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceDto>;
    })
  );
}

updateInvoiceStatus.PATH = '/api/Invoices/{id}/status';
