/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceDto } from '../../models/service-dto';

export interface GetServices$Params {
}

export function getServices(http: HttpClient, rootUrl: string, params?: GetServices$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceDto>>> {
  const rb = new RequestBuilder(rootUrl, getServices.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServiceDto>>;
    })
  );
}

getServices.PATH = '/api/Services';
