/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceDto } from '../../models/service-dto';
import { ServiceUpsertDto } from '../../models/service-upsert-dto';

export interface ServicesCreateService$Plain$Params {
  
    /**
     * The service creation data transfer object.
     */
    body?: ServiceUpsertDto
}

export function servicesCreateService$Plain(http: HttpClient, rootUrl: string, params?: ServicesCreateService$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceDto>> {
  const rb = new RequestBuilder(rootUrl, servicesCreateService$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceDto>;
    })
  );
}

servicesCreateService$Plain.PATH = '/api/Services';
